// flow-typed signature: dc92b4b3a2f160552d732ee766866b95
// flow-typed version: <<STUB>>/react-native-beacons-manager-new_vhttps://github.com/MacKentoch/react-native-beacons-manager-new.git/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-beacons-manager-new'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-beacons-manager-new' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-beacons-manager-new/examples/BeaconsDemo/__tests__/index.android' {
  declare module.exports: any;
}

declare module 'react-native-beacons-manager-new/examples/BeaconsDemo/__tests__/index.ios' {
  declare module.exports: any;
}

declare module 'react-native-beacons-manager-new/examples/BeaconsDemo/index.android' {
  declare module.exports: any;
}

declare module 'react-native-beacons-manager-new/examples/BeaconsDemo/index.ios' {
  declare module.exports: any;
}

declare module 'react-native-beacons-manager-new/examples/samples/monitoring.android' {
  declare module.exports: any;
}

declare module 'react-native-beacons-manager-new/examples/samples/monitoring.ios' {
  declare module.exports: any;
}

declare module 'react-native-beacons-manager-new/examples/samples/monitoringAndRanging.android' {
  declare module.exports: any;
}

declare module 'react-native-beacons-manager-new/examples/samples/monitoringAndRanging.ios' {
  declare module.exports: any;
}

declare module 'react-native-beacons-manager-new/examples/samples/multipleBeacon.range.ios' {
  declare module.exports: any;
}

declare module 'react-native-beacons-manager-new/examples/samples/ranging.android' {
  declare module.exports: any;
}

declare module 'react-native-beacons-manager-new/examples/samples/ranging.ios' {
  declare module.exports: any;
}

declare module 'react-native-beacons-manager-new/lib/module.android' {
  declare module.exports: any;
}

declare module 'react-native-beacons-manager-new/lib/module.ios' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-beacons-manager-new/examples/BeaconsDemo/__tests__/index.android.js' {
  declare module.exports: $Exports<'react-native-beacons-manager-new/examples/BeaconsDemo/__tests__/index.android'>;
}
declare module 'react-native-beacons-manager-new/examples/BeaconsDemo/__tests__/index.ios.js' {
  declare module.exports: $Exports<'react-native-beacons-manager-new/examples/BeaconsDemo/__tests__/index.ios'>;
}
declare module 'react-native-beacons-manager-new/examples/BeaconsDemo/index.android.js' {
  declare module.exports: $Exports<'react-native-beacons-manager-new/examples/BeaconsDemo/index.android'>;
}
declare module 'react-native-beacons-manager-new/examples/BeaconsDemo/index.ios.js' {
  declare module.exports: $Exports<'react-native-beacons-manager-new/examples/BeaconsDemo/index.ios'>;
}
declare module 'react-native-beacons-manager-new/examples/samples/monitoring.android.js' {
  declare module.exports: $Exports<'react-native-beacons-manager-new/examples/samples/monitoring.android'>;
}
declare module 'react-native-beacons-manager-new/examples/samples/monitoring.ios.js' {
  declare module.exports: $Exports<'react-native-beacons-manager-new/examples/samples/monitoring.ios'>;
}
declare module 'react-native-beacons-manager-new/examples/samples/monitoringAndRanging.android.js' {
  declare module.exports: $Exports<'react-native-beacons-manager-new/examples/samples/monitoringAndRanging.android'>;
}
declare module 'react-native-beacons-manager-new/examples/samples/monitoringAndRanging.ios.js' {
  declare module.exports: $Exports<'react-native-beacons-manager-new/examples/samples/monitoringAndRanging.ios'>;
}
declare module 'react-native-beacons-manager-new/examples/samples/multipleBeacon.range.ios.js' {
  declare module.exports: $Exports<'react-native-beacons-manager-new/examples/samples/multipleBeacon.range.ios'>;
}
declare module 'react-native-beacons-manager-new/examples/samples/ranging.android.js' {
  declare module.exports: $Exports<'react-native-beacons-manager-new/examples/samples/ranging.android'>;
}
declare module 'react-native-beacons-manager-new/examples/samples/ranging.ios.js' {
  declare module.exports: $Exports<'react-native-beacons-manager-new/examples/samples/ranging.ios'>;
}
declare module 'react-native-beacons-manager-new/index' {
  declare module.exports: $Exports<'react-native-beacons-manager-new'>;
}
declare module 'react-native-beacons-manager-new/index.js' {
  declare module.exports: $Exports<'react-native-beacons-manager-new'>;
}
declare module 'react-native-beacons-manager-new/lib/module.android.js' {
  declare module.exports: $Exports<'react-native-beacons-manager-new/lib/module.android'>;
}
declare module 'react-native-beacons-manager-new/lib/module.ios.js' {
  declare module.exports: $Exports<'react-native-beacons-manager-new/lib/module.ios'>;
}
